version: "3.9"

services:

  backend:
    build:
      context: ./backend
    container_name: backend-container
    ports:
      - "8000:8000"
    volumes:
      - ../faiss_db:/app/faiss_db   
      - ../uploaded_documents:/app/uploaded_documents         
    environment:
      - ENVIRONMENT_MODE=production
    env_file:
      - ./backend/.env
    restart: always

  embedder:
    build:
      context: ./embedder
    container_name: embedder-container
    ports:
      - "8001:8001"
    volumes:
      - ../faiss_db:/app/faiss_db 
      - ../uploaded_documents:/app/uploaded_documents    
    environment:
      - ENVIRONMENT_MODE=production
    env_file:
      - ./embedder/.env
    restart: always

  rag:
    build:
      context: ./rag
    container_name: rag-container
    ports:
      - "8002:8002"
    volumes:
      - ../faiss_db:/app/faiss_db   
    environment:
      - ENVIRONMENT_MODE=production
    env_file:
      - ./rag/.env

    restart: always

  web-app:
    build:
      context: ./web-app
    container_name: web-app-container
    ports:
      - "5000:5000" 
    environment:
      - ENVIRONMENT_MODE=production
    env_file:
      - ./web-app/.env
    depends_on:
      - backend
    restart: always

  phpmyadmin:
    image: phpmyadmin
    container_name: my-phpmyadmin
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_PORT=${PMA_PORT}
      - APACHE_AUTH_TYPE=Basic
      - APACHE_AUTH_USER=${APACHE_AUTH_USER}
      - APACHE_AUTH_PASSWORD=${APACHE_AUTH_PASSWORD}
      - PMA_ARBITRARY=0
      - PMA_ABSOLUTE_URI=${PMA_ABSOLUTE_URI}
    ports:
      - "8080:80"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - web-app
      - backend