version: "3.9"

services:
  rag-app:
    build:
      context: ./rag-app
    container_name: rag-app-container
    ports:
      - "8000:8000"
    volumes:
      - ./faiss_db:/app/faiss_db   
    environment:
      - ENVIRONMENT_MODE=production
    env_file:
      - ./rag-app/.env

    restart: always

  web-app:
    build:
      context: ./web-app
    container_name: web-app-container
    ports:
      - "80:5000" 
    environment:
      - ENVIRONMENT_MODE=production
    env_file:
      - ./web-app/.env
    depends_on:
      - rag-app
    restart: always

  phpmyadmin:
    image: phpmyadmin
    container_name: my-phpmyadmin
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_PORT=${PMA_PORT}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
      - APACHE_AUTH_TYPE=Basic
      - APACHE_AUTH_USER=${APACHE_AUTH_USER}
      - APACHE_AUTH_PASSWORD=${APACHE_AUTH_PASSWORD}
    ports:
      - "8080:80"
    restart: always
