name: Deploy QCM App

on:
  push:
    branches:
      - main  # Trigger deployment only on main branch

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: SSH and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            # Go to app directory or clone if it doesn't exist
            if [ ! -d "qcm-generator-rag-app" ]; then
              git clone https://github.com/${{ github.repository }}.git qcm-generator-rag-app
            fi
            cd qcm-generator-rag-app

            # Pull latest changes
            git pull origin main

            # Create .env file from GitHub secrets
            cat <<'EOT' > .env
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            NVIDIA_API_KEY=${{ secrets.NVIDIA_API_KEY }}
            # Add more secrets as needed
            EOT

            # Stop existing container (if running)
            sudo docker stop qcm-app || true
            sudo docker rm qcm-app || true

            echo "Building Docker image..."
            sudo docker build -t qcm-app . || { echo "Docker build failed"; exit 1; }

            echo "Listing Docker images..."
            sudo docker images || { echo "Failed to list Docker images"; exit 1; }

            echo "Running the Docker container..."
            sudo docker run -d --name qcm-app --env-file .env -p 80:8000 qcm-app || { echo "Docker run failed"; exit 1; }

            echo "Checking Docker container status..."
            sudo docker ps -a || { echo "Docker ps failed"; exit 1; }

            echo "Getting Docker container logs..."
            sudo docker logs qcm-app || { echo "Docker logs failed"; exit 1; }

            echo "Deployment finished."

          EOF
