name: Deploy QCM Generator App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: SSH and deploy
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            # Go to app directory or clone it if doesn't exist
            if [ ! -d "qcm-generator-rag-app" ]; then
              git clone https://github.com/MahmoudMoumni/qcm-generator-rag-app.git
            fi
            cd qcm-generator-rag-app

            # Pull the latest code
            git pull origin main

            # Create .env file from GitHub secrets
            cat <<EOT > .env
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            NVIDIA_API_KEY=${{ secrets.NVIDIA_API_KEY }}
            # Add more secrets here if needed
            EOT

            # Stop and remove existing container
            docker stop qcm-app || true && docker rm qcm-app || true

            # Rebuild Docker image
            docker build -t qcm-app .

            # Run container on port 80 (host) -> 8000 (container)
            docker run -d --env-file .env -p 80:8000 --name qcm-app qcm-app
          EOF
